[project]
name = "the-power-of-noise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.10.0",
    "datasets>=4.0.0",
    "einops>=0.8.1",
    "faiss-gpu-cu12>=1.11.0",
    "ijson>=3.4.0",
    "pandas>=2.3.2",
    "transformers>=4.55.4",
    "vllm>=0.10.1.1",
]

[tool.uv]
package = false
