llm_id: 'meta-llama/Llama-3.1-8B-Instruct'
model_max_length: 19200
max_new_tokens: 256
batch_size: 1024
tensor_parallel_size: 1
quantization_bits: null
gpu_memory_utilization: 0.8
eager_mode: false
debug: false
parse_reasoning: false
top_k: -1
top_p: 0.95
temperature: 0.0
presence_penalty: 0.0