defaults:
  - llm: llama3_3b
  - corpus: contriever
  - generation: ctx2_gold0_wAnswer
  - _self_
  - override hydra/launcher: joblib

# Data paths
data:
  data_path: 'data/test_dataset.json'
  full_corpus_path: 'data/corpus-widx.jsonl'

# Global settings
seed: 10

hydra:
  run:
    dir: ./output/${now:%Y-%m-%d-%H-%M}/${sanitize_path:${llm.llm_id}}-${corpus.retriever_str}/numdoc_${generation.num_documents_in_context}_answerless_${generation.get_documents_without_answer}_goldIdx_${generation.gold_position}/
  sweep:
    dir: ./sweeps/${now:%Y-%m-%d-%H-%M}/${sanitize_path:${llm.llm_id}}-${corpus.retriever_str}/numdoc_${generation.num_documents_in_context}_answerless_${generation.get_documents_without_answer}_goldIdx_${generation.gold_position}/